env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  -
    binary: telemetry
    ldflags: -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: telemetry
    homepage: "https://github.com/kubesphere/telemetry"
    tap:
      owner: kubesphere
      name: homebrew-tap
    commit_author:
      name: kubesphere
      email: info@kubesphere.io

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^assets:"
      - "^scripts:"
