name: CI
on:
  push:
    branches:
    - 'master'
    - 'release-**'
  pull_request:
jobs:
  ci:
    name: Lint and unit test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Environment
      run: |
        go version
        go env
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54
        args: --timeout=10m
    - name: Test
      run: make cover
